# Generated by Django 5.2.4 on 2025-07-20 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='car_make',
            field=models.ForeignKey(default=1, 
            null=True, 
            on_delete=django.db.models.deletion.CASCADE, 
            to='djangoapp.carmake'),
        ),
    ]
