# Generated by Django 5.2.4 on 2025-07-29 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_alter_carmodel_car_make'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='car_make',
            field=models.ForeignKey(
                                    null=True,
                                    on_delete=django.db.models\
                                    .deletion.CASCADE,
                                    to='djangoapp.carmake'
                                    ),
        ),
    ]
